### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name":"Noir",
  "email": "Noir@example.com",
  "address": "000 noir street",
  "dateOfBirth": "1998-12-21",
  "registeredDate": "2026-08-19"
}

###