### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name":"Jp with Kafka Consumer",
  "email": "Jp_kafkaConsumer_test1@example.com",
  "address": "021 Jump street",
  "dateOfBirth": "2001-12-21",
  "registeredDate": "2026-09-06"
}

###